---
- name: a playbook to setup my local machine with my basic customizations
  hosts: localhost
  connection: local
  vars:
    dotfiles_version: 'master'
    dot_home: "{{ ansible_user_dir }}/.dotfiles"
  environment:
    http_proxy: "{{ lookup('env','http_proxy') }}"

  roles:
    - common
#    - dotfiles
#    - { role: git, become: yes }
#    - { role: laptop, tags: [ 'never','laptop'] }

