---

- name: a playbook to setup my local machine with my basic customizations
  hosts: local
  connection: local
  
  tasks:
    - name: test de connexion
      ping:
      
    - name: Recuperation  
      shell: wget https://github.com/atom/atom/releases/download/v1.22.0/atom-amd64.deb -O files/atom.deb
  
    #- name: installation de Atom
    #  apt: 
    #    deb:"https://github.com/atom/atom/releases/download/v1.22.0/atom-amd64.deb"
    # not working w/ vagrant - trusty64
     
    
...
