---

- name: a playbook to setup my local machine with my basic customizations
  hosts: local
  connection: local


  roles:
    - common

  tasks:

    - name: Recuperation
      shell: wget https://github.com/atom/atom/releases/download/v1.22.0/atom-amd64.deb -O atom.deb
      args:
        creates: atom.deb

    - name: Decommente "#force_color_prompt=yes" ligne 46 de .bashrc
      lineinfile:
        path: "{{ ansible_user_dir }}/bashrc"
        regexp: '#?\s*force_color_prompt='
        line: force_color_prompt=yes



...
