---

- name: a playbook to setup my local machine with my basic customizations
  hosts: localhost
  connection: local

  roles:
    - import_role:
      name: atom
      vars:
        atom_home: "{{ ansible_user_dir }}/.atom"
        dot_home: "{{ ansible_user_dir }}/dotfiles"
    #- laptop

#comment laptop if in a VM
...
