---

- name: a playbook to setup my local machine with my basic customizations
  hosts: local
  connection: local
  
  tasks:
    - name: test de connexion
      ping:
      
    - name: Recuperation  
      shell: wget https://github.com/atom/atom/releases/download/v1.22.0/atom-amd64.deb -O atom.deb
      args:
        creates: atom.deb
        
    - name: Installation de paquets généraux
      apt:
        name: "{{ item }}"
        state: present
      with_items:
         - tree
         - synaptic
         - cowsay
         - python
         - python-pip
      become: yes
         
    - name: Installation pip
      pip:
        name: "{{ item }}"
        state: present
      with_items:
         - virtualenv
         - Fabric
      become: yes
...
