---
- name: DOT | Copy dotfiles repo
  git:
    repo: "https://github.com/watysay/dotfiles.git"
    dest: "{{ dot_home }}"

- name: DOT | Stow dotfiles content
  shell: "/usr/bin/stow -Rn {{ item }}"
  args:
    chdir: "{{ dot_home }}"
  loop:
    - atom
    - bash
    - git
    - vim
