---
- name: Add git repo to repo list
  apt_repository:
    repo: ppa:git-core/ppa
    update_cache: yes

- name: update cache and install git
  apt:
    name: git
    state: latest

- name: get git version
  shell: "$(which git) --version | cut -d' ' -f3"
  register: git_version

- name: show git version retrieved
  debug:
    var: git_version

- name: retrieve git-completion script
  get_url:
    url: https://raw.githubusercontent.com/git/git/v{{ git_version.stdout }}/contrib/completion/git-completion.bash
    dest: /etc/bash_completion.d/git-completion

- name: retrieve git-prompt script
  get_url:
    url: https://raw.githubusercontent.com/git/git/v{{ git_version.stdout }}/contrib/completion/git-prompt.sh
    dest: /etc/bash_completion.d/git-prompt
