---
- name: Install Atom directly from internet
  apt:
    deb: https://atom.io/download/deb
  become: yes
  register: result
  ignore_errors: True

- name: Install Atom directly from internet
  block:
    - name: Retrieve Atom from internet
      shell: "wget https://atom.io/download/deb -O /tmp/atom.deb"
      args:
        creates: "/tmp/atom.deb"

    - name: Install Atom retrieved earlier
      apt:
        deb: "/tmp/atom.deb"

  when: result is failed
  become: yes

- name: Retrieve apm installer
  shell: "which apm"
  register: apm_installer

- name: debug
  debug:
    var: apm_installer
    verbosity: 1

- name: Backup default configuration
  copy:
    src: "{{ atom_home }}/config.cson"
    dest: "{{ atom_home }}/config.cson.backup"

- name: Backup default configuration
  file:
    path: "{{ atom_home }}/config.cson"
    state: absent

- name: Copy configuration
  file:
    src: "{{ role_path }}/files/{{ item }}"
    path: "{{ atom_home }}/{{ item }}"
    state: link
  with_items:
    - config.cson
    - packages.txt
    - themes.txt

- name: Changing config proxy
  shell: "{{ apm_installer.stdout }} config set proxy {{ lookup('env', 'http_proxy') }}"

- name: Changing config https_proxy
  shell: "{{ apm_installer.stdout }} config set https_proxy {{ lookup('env', 'https_proxy') }}"

- name: install packages  and themes
  shell: "{{ apm_installer.stdout }} install --packages-file {{ item }}"
  args:
    chdir: "{{ atom_home }}"
  with_items:
    - packages.txt
    - themes.txt

# manual install (proxy ko ?): wget URL -O atom.deb && sudo dpkg -i atom.deb
# retrieve:
#  apm list --installed --bare --themes > themes.txt
#  apm list --installed --bare --packages > packages.txt
