---
- name: Install Atom directly from internet
  apt:
    deb: https://atom.io/download/deb
  become: yes
  register: result
  ignore_errors: True

# only after dotfiles are processed..
# 1 is install atom
# 2 is install dotfiles
# 3 is installing packages & themes

# manual install (proxy ko ?): wget URL -O atom.deb && sudo dpkg -i atom.deb

- name: Install Atom directly from internet
  block:
    - name: Retrieve Atom from internet
      shell: "wget https://atom.io/download/deb -O /tmp/atom.deb"
      args:
        creates: "/tmp/atom.deb"


    - name: Install Atom retrieved earlier
      apt:
        deb: "/tmp/atom.deb"

  when: result is failed
  become: yes

- name: Copy configuration
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/atom/.atom/"
    backup: yes
  loop:
    - config.cson
    - packages.txt
    - themes.txt
