---
- name: Install Atom directly from internet
  apt:
    deb: https://atom.io/download/deb
  become: yes

# only after dotfiles are processed..
# 1 is install atom
# 2 is install dotfiles
# 3 is installing packages & themes
# - name: Installing packages and themes
#   shell: "/usr/bin/apm install --packages-file {{ atom_home }}/{{ item }}"
#   loop:
#     - packages.txt
#     - themes.txt
