---
- name: DOT | Copy dotfiles repo
  synchronize:
    src: "{{ playbook_dir }}/dotfiles"
    dest: "{{ ansible_user_dir }}"
    recursive: yes
  delegate_to: localhost

- name: DOT | Stow dotfiles content
  shell: "/usr/bin/stow -Rn {{ item }}"
  args:
    chdir: "{{ ansible_user_dir }}/dotfiles"
  loop:
    - atom
    - bash
    - git
    - vim
