---
- name: Installation de paquets généraux
  import_tasks: general.yml

- name: ATOM | Installation atom
  import_tasks: atom.yml
  tags: atom

- name: DOT | Installation dotfiles
  import_tasks: dotfiles.yml
  tags: dot

- name: END | ending installation for role
  import_tasks: end.yml
  tags: end
