---
- name: Installation de paquets généraux
  apt:
    name: "{{ item }}"
    state: present
  with_items:
     - tree
     - git
     - plank
     - vim
     - synaptic
     - python
     - python-pip
  become: yes

- name: Installation pip
  pip:
    name: "{{ item }}"
    state: present
  with_items:
     - virtualenv
     - Fabric
  become: yes  
