---
- name: Installation de paquets généraux
  become: yes
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - tree
    - git
    - plank
    - vim
    - htop
    - synaptic
    - python
    - stow
    - python-pip

- name: Installation pip
  become: yes
  pip:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - virtualenv
    - Fabric

- name: Installation atom
  import_tasks: atom.yml
