---
- name: Installation de paquets généraux
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - git
    - htop
    - plank
    - python
    - python-pip
    - rsync
    - stow
    - synaptic
    - tree
    - vim

- name: Installation pip
  become: yes
  pip:
    name: "{{ item }}"
    state: latest
  loop:
    - virtualenv
    - Fabric

# - name: Installation atom
#   import_tasks: atom.yml
#   vars:
#     atom_home: "{{ ansible_user_dir }}/.atom"

- name: Installation dotfiles
  import_tasks: dotfiles.yml
  
