---
- name: Mise a jour apt
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 18000

- name: Installation de paquets généraux
  become: yes
  apt:
    name: "{{ packages }}"
    state: present

- name: Installation pip
  become: yes
  pip:
    name: "{{ pip_packages }}"
    state: present
