---
- name: Installation de paquets généraux
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
     - tree
     - git
     - plank
     - vim
     - htop
     - synaptic
     - python
     - python-pip

- name: Installation pip
  become: yes
  pip:
    name: "{{ item }}"
    state: present
  with_items:
     - virtualenv
     - Fabric
