---
- name: Installation de paquets généraux
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - tree
    - git
    - plank
    - vim
    - htop
    - synaptic
    - python
    - stow
    - python-pip

- name: Installation pip
  become: yes
  pip:
    name: "{{ item }}"
    state: latest
  loop:
    - virtualenv
    - Fabric

# - name: Installation atom
#   import_tasks: atom.yml
#   vars:
#     atom_home: "{{ ansible_user_dir }}/.atom"
